name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          mkdir -p assets
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > assets/.env
          echo "SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }}" >> assets/.env
          echo "SANITY_DATASET=${{ secrets.SANITY_DATASET }}" >> assets/.env

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@f389f417f5f922718e268f7f2b9826359e19574d
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DESIGNWEAR_APP_8984 }}'
          channelId: live
          projectId: designwear-app-8984
