name: Flutter CI

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: flutter pub get

      - name: Create .env file
        run: |
          mkdir -p assets
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > assets/.env
          echo "SANITY_PROJECT_ID=${{ secrets.SANITY_PROJECT_ID }}" >> assets/.env
          echo "SANITY_DATASET=${{ secrets.SANITY_DATASET }}" >> assets/.env

      - name: Write google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run Tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk


